Personal_Website/urls.py
from django.contrib import admin
from django.urls import path,include
from first_version.views import home
from first_version.views import feedback
from first_version.views import register
from first_version.views import activity
from first_version.views import schedule
from first_version.views import saveactivity
from first_version.views import display_schedule
from first_version.views import success
from first_version.views import delete_schedule




urlpatterns = [
    path('admin/', admin.site.urls),
    # path('feedback/', feedback),
    # path('home/', home),
    # path('register/', register),
    # path('activity/',activity),
    # path('schedule/',schedule),
    # path('save_activity/',saveactivity),
    # path('display_schedule/',display_schedule),
    # path('success/',success),
    path('',include(('first_version.urls','first_version'),namespace='first_version')),
    # path('schedule_delete/',delete_schedule),
   # path('',include('first_version.urls'))
]

first_version/urls.py
from django.urls import re_path
from django.urls import path
from .views import home,feedback,register,activity,schedule,saveactivity,display_schedule,success,delete_schedule
#url for app
 
 #path('',home, name='home'),
  #  path('feedback/',feedback, name='feedback'),
   # path('register/',register, name='register'),
    #path('activity/',activity,name='activity'),
    #re_path(r'^$',home, name='home'),
    #re_path(r'^feedback/$',feedback, name='feedback'),
    #re_path(r'^register/$',register, name='register'),
    #re_path(r'^activity/$',activity,name='activity'),
urlpatterns = [
   path('',home, name='home'),
    path('feedback/',feedback, name='feedback'),
    path('register/',register, name='register'),
    path('activity/',activity,name='activity'),
    path('schedule/',schedule,name='schedule'),
     path('save_activity/',saveactivity,name='saveactivity'),
      path('display_schedule/',display_schedule,name='display_schedule'),
      path('success/',success,name='success'),
      path('schedule_delete/',delete_schedule,name='delete_schedule')


 
    
  
]
   

first_version/models.py
from django.db import models
from django.utils import timezone

class Activity(models.Model):
   
    activity = models.CharField(max_length=200)
    place = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    date = models.DateField()
    time = models.TimeField()
    created_date = models.DateTimeField(default=timezone.now)



# Create your models here.

first_version/forms.py
from django import forms

class Activity_Form(forms.Form):
   
    error_messages = {
        'required': 'Please type',
    }
    activity_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder': 'activity'
        
    }
    place_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'place'
    }
    category_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'category'
    }
    date_attrs={
        'type':'date'
        
    }

    category_choices=(
        ('indoor','indoor'),
        ('outdoor','outdoor'),
        ('a bit of both','a bit of both'),
    )

    activity = forms.CharField(label='Activity', required=True, max_length=27, widget=forms.TextInput(attrs=activity_attrs))
    place = forms.CharField(label='Place', required=True, max_length=27, widget=forms.TextInput(attrs=place_attrs))
    #category = forms.CharField(label='Category', required=True,max_length=27,choices=category_choices)
    category = forms.ChoiceField(label='Category', required=True,choices=category_choices)
    #date = forms.CharField(label='Date', required=True, max_length=27, widget=forms.DateInput(attrs=date_attrs))
    date = forms.DateField(label='Date',required=True,widget=forms.DateInput(attrs=date_attrs))
    time = forms.TimeField(label='Time',required=True,widget=forms.TimeInput(attrs={'type':'time'}))

first_version/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Activity_Form
from .models import Activity

response={}

def home(request):
    #response={}
    return render(request,'homepage.html',response)
def feedback(request):
    #response={}
    return render(request,'feedback.html',response)
def register(request):
    #response={}
    return render(request,'Form_Register_Account.html',response)
def schedule(request):
    return render(request,'schedule.html',response)
def success(request):
    return render(request,'success.html',response)
def activity(request):
    response['title'] = 'Add Activity'
    response['add_activity_form'] =  Activity_Form()
    return render(request,'activity.html',response)
def saveactivity(request):
    form = Activity_Form(request.POST or None)
    if(request.method=='POST' and form.is_valid()):
        response['activity']= request.POST['activity']
        response['place']=request.POST['place']
        response['category']=request.POST['category']
        response['date'] = request.POST['date']
        response['time'] = request.POST['time']

        Activities= Activity(
            activity=response['activity'],
            place=response['place'],
            category=response['category'],
            date=response['date'],
            time=response['time']
        )
        Activities.save()
        return render(request,'success.html',response)
    else:
        return HttpResponseRedirect('/')
def display_schedule(request):
    all_schedules = Activity.objects.all()
    response['all_schedules'] = all_schedules
    return render(request,'schedule.html',response)
def delete_schedule(request):
    print("1")
    Activity.objects.all().delete()
    print("2")
    return HttpResponseRedirect('/display_schedule')





# Create your views here.

first_version/templates/Form_Register_Account.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}
<!--<head>
        <title>Register</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
       <link rel="stylesheet" type="text/css" href="{% static 'css.css' %}"> 
        <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 
</head>
<body>
  
    <div>

        <nav class="navbar navbar-expand-lg navbar-light bg-dark ">
           
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav ml-auto">
              
              <li><a class="nav-item nav-link " href="{% url 'home' %}"  style="color:white;padding: 10px 25px;">Home</a></li> 
              <li><a class="nav-item nav-link" href="{% url 'feedback' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Feedback</a></li> 
               <li><a class="nav-item nav-link" href="contact"style="color:white;  margin: 0px;padding: 10px 25px;">Contact Me</a></li>
               <li><a class="nav-item nav-link" href="{% url 'register' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Register</a></li>
               
               
             </div>
           </div>
         </nav>


   </div> 
   <!-- </div> -->
   {% block content %}
   <div class="container-fluid">
     <div class="row">
       <div class = "col-sm-12">
          <h1 id="head1">Register Account</h1>

       </div>

     </div>

     <div class = "row">
        <div class = "col-sm-12">
            <h2 id="head2" >Please complete the form below to continue</h2>

          </div>

     </div>

     <div class = "row">
        <div class = "col-sm-12">
            <div>
                
                <div class="container" style="margin-top: 150px; background-color: #f2f2f2;padding: 20px;">
                  <form >
                    <div class="row">
                      <div class="col-25">
                        <label for="fname">First Name</label>
                      </div>
                      <div class="col-75">
                        <input type="text" id="name" name="firstname" placeholder="Name">
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-25">
                        <label for="lname">Date of Birth</label>
                      </div>
                      <div class="col-75">
                        <input type="text" id="dob" name="Date of birth" placeholder="Date of birth">
                      </div>
                    </div>
                    
                    <div class="row">
                      <div class="col-25">
                        <label for="subject">E-mail</label>
                      </div>
                      <div class="col-75">
                            <input type="text" id="email" name="E-Mail" placeholder="E-Mail">
                      </div>
                    </div>

                    <div class="row">
                            <div class="col-25">
                              <label for="subject">Username</label>
                            </div>
                            <div class="col-75">
                                  <input type="text" id="username" name="Username" placeholder="Username">
                            </div>
                    </div>

                    <div class="row">
                            <div class="col-25">
                              <label for="pwd">Password</label>
                            </div>
                            <div class="col-75">
                                  <input type="password" id="pwd" name="Password" placeholder="Password" class="form-control">
                            </div>
                    </div>

                    <div class="row">
                            <div class="col-25">
                              <label for="pwd">Confirm Password</label>
                            </div>
                            <div class="col-75">
                                    <input type="password" id="pwd" name="Password" placeholder="Password" class="form-control">
                            </div>
                    </div>
                    <br>

                    <div class="row">
                      <input type="submit" value="Submit">
                    </div>
                  </form>
                </div>

          </div>

     </div>
     

   </div>
   {% endblock content %}
   
   
    
    
    <div>
      

        

        </div>
        
        
<!--</body>

first_version/templates/activity.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}
 {% block content %}

 <div class="container-fluid">
     <div class="row">
         <div class="col-sm-12">
                <h1 id="head1">Activity</h1>
                <h2 id="head2" >Please fill in the form for new activities</h2>
         </div>

     </div>

     <div class="row">
         <div class="col-sm-9">
                <form id="form" method="POST" action="{% url 'first_version:saveactivity' %}">
                        {% csrf_token %}
                        {{ add_activity_form.as_p }}
                        <input  type="submit" value="Submit">
                 </form>

         </div>
         
         
    </div>
 </div>
 {% endblock content %}

first_version/templates/feedback.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}
<!--<head>
        <title>Feedback</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
       <link rel="stylesheet" type="text/css" href="{% static 'css.css' %}"> 
        <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 
</head>

<body>
    <div>

        <nav class="navbar navbar-expand-lg navbar-light bg-dark ">
           <!-- <a class="navbar-brand" href="#">Vincentius Adi</a> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav ml-auto">
               <!-- <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a> 
              <li><a class="nav-item nav-link " href="{% url 'home' %}"  style="color:white;padding: 10px 25px;">Home</a></li> 
              <li><a class="nav-item nav-link" href="{% url 'feedback' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Feedback</a></li> 
               <li><a class="nav-item nav-link" href="contact"style="color:white;  margin: 0px;padding: 10px 25px;">Contact Me</a></li>
               <li><a class="nav-item nav-link" href="{% url 'register' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Register</a></li>
               
               
             </div>
           </div>
         </nav> -->


   </div>

   {% block content %}
   <div class="container-fluid">
     <div class="row">
       <div class="col-sm-12" style="background-color: ">
          <h1 id="head1">Feedback</h1>

       </div>
        

     </div>
     <br>
     <div class="row">
        <div class="col-sm-12" style="background-color:" id ="shortdesc">
            <p >
                As a programmer, we always do maintanance in order to keep our program sharp. 
                The same is true for us isn't it? As a human being I'm a firm believer of constant improvement. 
                I realized that there must be a thing or two or more that I can improve on, and of course it will be only possible by the contribution of your feedbacks
        </br>
    </br>
        So please, If you had anything to say, don't ever feel hesitate to fill in the space below. I will appreciate any kind of feedbacks as long as it is still relevant.
        </p>

          
         </div>


      </div>
      <br>
      <div class="row">
        <div class="col-sm-12">
            <div class="container" style="margin-top: 150px; background-color: #f2f2f2; padding: 20px">
                <form >
                  <div class="row">
                    <div class="col-25">
                      <label for="fname">First Name</label>
                    </div>
                    <div class="col-75">
                      <input type="text" id="fname" name="firstname" placeholder="Your name..">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-25">
                      <label for="lname">Last Name</label>
                    </div>
                    <div class="col-75">
                      <input type="text" id="lname" name="lastname" placeholder="Your last name..">
                    </div>
                  </div>
                  
                  <div class="row">
                    <div class="col-25">
                      <label for="subject">Subject</label>
                    </div>
                    <div class="col-75">
                      <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>
                    </div>
                  </div>
                  <div class="row">
                    <input type="submit" value="Submit">
                  </div>
                </form>
              </div>

        </div>
          

        </div>



   </div>
   {% endblock content %}
        

        <div>
               
              
        </div> 
        
        <div>
                
                

        </div>
</body>

first_version/templates/navbar.html
<!DOCTYPE html>
{% load static %}
 {% load staticfiles %}
<head>
      
    <title>Homepage</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    
   <link rel="stylesheet" type="text/css" href="{% static 'css.css' %}"> 
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> 

</head>

<body>
    <div>

        <nav class="navbar navbar-expand-lg navbar-light bg-dark ">
           
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav ml-auto">
            
              <li><a class="nav-item nav-link " href="{% url 'first_version:home' %}"  style="color:white;padding: 10px 25px;">Home</a></li> 
               <li><a class="nav-item nav-link" href="{% url 'first_version:feedback' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Feedback</a></li> 
               <!-- <li><a class="nav-item nav-link" href="contact"style="color:white;  margin: 0px;padding: 10px 25px;">Contact Me</a></li> -->
                <li><a class="nav-item nav-link" href="{% url 'first_version:register' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Register</a></li>
                <li><a class="nav-item nav-link" href="{% url 'first_version:activity' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Add Activity</a></li>
                <li><a class="nav-item nav-link" href="{% url 'first_version:display_schedule' %}"style="color:white;  margin: 0px;padding: 10px 25px;">Schedule</a></li>
            
               
             </div>
           </div>
         </nav>


   </div> 
   {% block content %}
   {% endblock %}

</body>



        

first_version/templates/schedule.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}
 {% block content %}
 <div class="container-fluid">
     <div class="row">
            <div class="col-sm-12">
                    <h1 id="head1">Schedule</h1>
             </div>
     </div>
     <br>
     <br>
     <div class="row">
            {% for data in all_schedules %}
            <div class="col-sm-12">
                <a id ="head2" style="font-size: 30px"> Activity : {{ data.activity }}</a><br>
                <a id ="head2" style="font-size: 30px"> Place : {{ data.place }}</a><br>
                <a id ="head2" style="font-size: 30px"> Category : {{ data.category }}</a><br>
                <a id ="head2" style="font-size: 30px"> Date : {{ data.date | date:"l, d M Y" }}</a><br>
                <a id ="head2" style="font-size: 30px"> Time : {{ data.time | time:"h:i A" }}</a>
                <br>
                <br>
                    
             </div>
             
             {% endfor %}
     </div>
     <form action="{% url 'first_version:delete_schedule' %}" method="POST" >
         {% csrf_token %}
         <input class="btn btn-default btn-danger" type ="submit" value="Delete All"/>
     </form>
     

 </div>
 {% endblock content %}

first_version/templates/success.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
 {% load staticfiles %}
 {% block content %}
 <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                   <h1 id="head1">Success !</h1>
                   <h2 id="head2" >You've added a new activity!</h2>
            </div>
   
        </div>


 {% endblock content %}